# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

idade_Renata = 14
idade_Fabiana = 18
dinheiro_iara = 5,000

if (idade_Renata >=14 and idade_Fabiana == 18 or dinheiro_iara == 5,000 ):
    situação = 'vai viajar'
else:
    situação = 'nao vai viajar' 

print(f'Rodrigo {situação} para portugal')

saber_sambar = 'sim'
gostar_feijoada = 'não'
torcerseleçaobrasileira = 'sim'

if (saber_sambar >='sim' and gostar_feijoada == 'sim' or torcerseleçaobrasileira == 'sim'):
    print ('Esse é brasileiro')
else:
 print('Esse não é brasileiro')

TD = 'sim'
TF = 'não'
Gosta = 'sim'

if TD == 'sim':
   TDcondinçao = 'verdadeiro'
elif TD == 'não':
     TDcondiçao = 'falso'

if TF == 'sim':
    TFcondiçao = 'verdadeiro'
elif TF == 'não': 
     TFcondiçao = 'falso'
   
if Gosta == 'sim':
    Gcondiçao = 'verdadeiro'
elif Gosta == 'não':
     Gcondiçao = 'falso'


if Gcondiçao == 'falso' or TFcondiçao == 'falso':
    GTFcondiçao = 'falso'
else:
    GTFcondiçao = 'verdadeiro'


if GTFcondiçao == 'verdadeiro' and TDcondiçao == 'verdadeiro':
    Fcondiçao = 'verdadeiro'
else: 
    Fcondiçao = 'falso'

print(f'A pessoa tem dentes {TDcondiçao} e ter fome {TFcondiçao} ou gostar de maça {Gcondiçao}')