# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""



aluno = input(' digite o nome do aluno:')
n1 = int(input('digite a primeira nota' ))
n2 = int(input('digite a segunda nota' ))
n3 = int(input('digite a terceira nota' ))
media = (n1+n2+n3)/3
if media >= 7:
    situaçao = 'aprovado'
elif media >= 4:
    situaçao = 'Em recuperaçao'
else:
    situaçao = 'reprovado'
print(f'O Aluno {aluno} esta em Situaçao {situaçao} com media {media}')